spring.application.name=jogospessoaidosa
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.data.mongodb.uri=mongodb://admin:senha123@localhost:27017/jogosdapessoaidosa?authSource=admin

